DROP TABLE IF EXISTS FUNKOS;
CREATE TABLE IF NOT EXISTS FUNKOS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    cod UUID NOT NULL DEFAULT UUID(),
    nombre VARCHAR(255),
    modelo ENUM('MARVEL', 'DISNEY', 'ANIME', 'OTROS'),
    precio DECIMAL(10, 2),
    fecha_lanzamiento DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );
