DROP TABLE IF EXISTS FUNKOS;
CREATE TABLE FUNKOS
(
    ID                UUID AUTO_INCREMENT PRIMARY KEY,
    COD               UUID NOT NULL DEFAULT UUID(),
    NOMBRE            VARCHAR(255),
    MODELO            ENUM('MARVEL', 'DISNEY', 'ANIME', 'OTROS'),
    PRECIO            DECIMAL(10,2),
    FECHA_LANZAMIENTO DATE,
    CREATED_AT        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT        TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);